/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AAE.AAE;
import AAE.Login;
import AAE.Serializer;
import AAE.UserAuthenticationFailedException;
import AAE.UserNotFoundException;
import java.awt.*;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Carlos
 */
public class LoginFR extends javax.swing.JFrame {
    
        private static MainFR main;
        private static Login login;
        private AAE aae;
    /**
     * Creates new form Login
     */
    public LoginFR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        QuitLabel = new javax.swing.JLabel();
        LogoCNE = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        UsernameLabel.setText("Username");
        UsernameLabel.setFocusable(false);
        jPanel1.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 110, 30));

        PasswordLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");
        PasswordLabel.setFocusable(false);
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 90, 30));

        LoginButton.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setFocusPainted(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 110, 40));

        QuitLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        QuitLabel.setForeground(new java.awt.Color(204, 0, 0));
        QuitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuitLabel.setText("Quit");
        QuitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitLabelMouseClicked(evt);
            }
        });
        jPanel1.add(QuitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 526, 80, 40));

        LogoCNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CNE.png"))); // NOI18N
        jPanel1.add(LogoCNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        UsernameField.setBackground(new java.awt.Color(204, 204, 204));
        UsernameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 270, 50));

        PasswordField.setBackground(new java.awt.Color(204, 204, 204));
        PasswordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
           String x= null;
            try {
                if (login.authenticateUser(UsernameField.getText(),PasswordField.getText())) {
                    main = new MainFR(this,aae);
                    //Shows Menu interface upon LoginFR success
                    main.setVisible(true);
                    this.setVisible(false);
                    resetValues(0);
                }    
            } catch (UserNotFoundException ex) {
              new Popup(this,false, "Utilizador inválido");
            } catch (UserAuthenticationFailedException ex) {
                new Popup(this,false, "Password Inválida");
            } catch (Exception ex) {
                new Popup(this,false, "Erro");
            }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void QuitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitLabelMouseClicked
        System.exit(1);
    }//GEN-LAST:event_QuitLabelMouseClicked

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    new LoginFR().setVisible(true);
                    
                    try {
                //Control information to send
                    login = (Login)Serializer.readObject("AAE.Login");
                   
                    } catch (IOException  | ClassNotFoundException ex) {
                  ex.printStackTrace(); 
            }
                } catch (Exception e) {
                    e.printStackTrace();
		}
            }
        });
    }
    public void resetValues(int type) {
        switch (type) {
            case 0:
                UsernameField.setText("");
                PasswordField.setText("");
                break;
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton LoginButton;
    private javax.swing.JLabel LogoCNE;
    private javax.swing.JPasswordField PasswordField;
    private static javax.swing.JLabel PasswordLabel;
    private static javax.swing.JLabel QuitLabel;
    private javax.swing.JTextField UsernameField;
    private static javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
