/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import AAE.AAE;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Carlos
 */
public class MainFR extends javax.swing.JFrame {

    private LoginFR loginFrame;
    private MenuFR menuFrame;
    private AAE aae;    
    
    /**
     * Creates new form Main
     */
    public MainFR() {
        initComponents();
    }
    
    public MainFR(LoginFR lg , AAE a) {
        initComponents();
        loginFrame = lg;
        menuFrame = new MenuFR();
        aae = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoCNE = new javax.swing.JLabel();
        CAEButton = new javax.swing.JButton();
        GAEButton = new javax.swing.JButton();
        LogoutLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(945, 571));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoCNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CNE.png"))); // NOI18N
        jPanel1.add(LogoCNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        CAEButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CAEButton.setText("Configurar Acto Eleitoral");
        CAEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAEButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CAEButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 230, 50));

        GAEButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        GAEButton.setText("Gerir Acto Eleitoral");
        GAEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAEButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GAEButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 230, 50));

        LogoutLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(204, 0, 0));
        LogoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutLabel.setText("Logout");
        jPanel1.add(LogoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 30));

        LogoutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoutIcon.png"))); // NOI18N
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CAEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAEButtonActionPerformed
        menuFrame = new MenuFR(this, aae);
        menuFrame.setVisible(true);
        menuFrame.VisibleCAE();
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CAEButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        loginFrame.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void GAEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAEButtonActionPerformed
        menuFrame = new MenuFR(this, aae);
        menuFrame.setVisible(true);
        menuFrame.VisibleGAE();
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_GAEButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    new MainFR().setVisible(true);
                    
                }catch (Exception e) {
                    e.printStackTrace();
                }
        }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CAEButton;
    private javax.swing.JButton GAEButton;
    private javax.swing.JLabel LogoCNE;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
