/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Carlos
 */
public class MenuFR extends javax.swing.JFrame {

    private MainFR mainFrame;
    /**
     * Creates new form CAE
     */
    public MenuFR() {
        initComponents();
    }
    
    public MenuFR(MainFR m) {
        initComponents();
        mainFrame = m;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        LogoCNE = new javax.swing.JLabel();
        GerirActoEleitoral = new javax.swing.JPanel();
        RegistarVotos = new javax.swing.JButton();
        DeclararVencedor = new javax.swing.JButton();
        AtribuirMandatos = new javax.swing.JButton();
        GerarEstatísticas = new javax.swing.JButton();
        Back1 = new javax.swing.JButton();
        GerarEstatísticasPanel = new javax.swing.JPanel();
        Confirmar3 = new javax.swing.JButton();
        Eleicao2 = new javax.swing.JLabel();
        Lista2 = new javax.swing.JLabel();
        EleicaoComboBox2 = new javax.swing.JComboBox();
        ListaComboBox1 = new javax.swing.JComboBox();
        ImagemListaLabel2 = new javax.swing.JLabel();
        CirculoLabel = new javax.swing.JLabel();
        CirculoComboBox = new javax.swing.JComboBox();
        PercentagemTextField2 = new javax.swing.JTextField();
        Percentagem1 = new javax.swing.JLabel();
        CandidatosLabel1 = new javax.swing.JLabel();
        CandidatosComboBox1 = new javax.swing.JComboBox();
        RegistarVotosPanel = new javax.swing.JPanel();
        LocalizacaoLabel = new javax.swing.JLabel();
        VRLabel = new javax.swing.JLabel();
        VVLabel = new javax.swing.JLabel();
        LocalizacaoTextField = new javax.swing.JTextField();
        VRTextField = new javax.swing.JTextField();
        VVTextField = new javax.swing.JTextField();
        Confirmar2 = new javax.swing.JButton();
        SButton = new javax.swing.JButton();
        DeclararVencedorPanel = new javax.swing.JPanel();
        Confirmar1 = new javax.swing.JButton();
        ImagemListaLabel1 = new javax.swing.JLabel();
        Lista1 = new javax.swing.JLabel();
        PartidosComboBox1 = new javax.swing.JComboBox();
        Eleicao1 = new javax.swing.JLabel();
        Percentagem = new javax.swing.JLabel();
        PercentagemTextField1 = new javax.swing.JTextField();
        EleicaoComboBox1 = new javax.swing.JComboBox();
        CandidatosLabel = new javax.swing.JLabel();
        CandidatosComboBox = new javax.swing.JComboBox();
        AtribuirMandatosPanel = new javax.swing.JPanel();
        Eleicao = new javax.swing.JLabel();
        Lista = new javax.swing.JLabel();
        Deputados = new javax.swing.JLabel();
        EleicaoComboBox = new javax.swing.JComboBox();
        ListaComboBox = new javax.swing.JComboBox();
        DeputadosTextField = new javax.swing.JTextField();
        ImagemListaLabel = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        ConfigurarActoEleitoral = new javax.swing.JPanel();
        RegistarEleição = new javax.swing.JButton();
        AdicionarListas = new javax.swing.JButton();
        AdicionarCandidatos = new javax.swing.JButton();
        AdicionarVotantes = new javax.swing.JButton();
        GerirAssembleias = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        AdicionarCandidatosPanel = new javax.swing.JPanel();
        Confirmar7 = new javax.swing.JButton();
        EleiçãoLabel1 = new javax.swing.JLabel();
        BILabel = new javax.swing.JLabel();
        NomeLabel = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        ArquivoLabel = new javax.swing.JLabel();
        DatadeNascimentoLabel = new javax.swing.JLabel();
        NaturalidadeLabel = new javax.swing.JLabel();
        Filiação = new javax.swing.JLabel();
        Morada = new javax.swing.JLabel();
        EleiçãoComboBox = new javax.swing.JComboBox();
        BITextField1 = new javax.swing.JTextField();
        NomeTextField2 = new javax.swing.JTextField();
        RuaTextField3 = new javax.swing.JTextField();
        LocalidadeTextField4 = new javax.swing.JTextField();
        CodigoPostalTextField = new javax.swing.JTextField();
        NaturalidadeTextField = new javax.swing.JTextField();
        FiliaçãoTextField7 = new javax.swing.JTextField();
        ArquivoTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        RegistarEleiçãoPanel = new javax.swing.JPanel();
        Confirmar5 = new javax.swing.JButton();
        EleiçãoComboBox1 = new javax.swing.JComboBox();
        EleiçãoLabel2 = new javax.swing.JLabel();
        DataLabel1 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        EleiçãoLabel3 = new javax.swing.JLabel();
        EleiçãoComboBox2 = new javax.swing.JComboBox();
        AdicionarListasPanel = new javax.swing.JPanel();
        Confirmar6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        AdicionarVotantesPanel = new javax.swing.JPanel();
        Confirmar8 = new javax.swing.JButton();
        GerirAssembleiasPanel = new javax.swing.JPanel();
        EleicaoLabel = new javax.swing.JLabel();
        FreguesiaLabel = new javax.swing.JLabel();
        PresidenteLabel = new javax.swing.JLabel();
        VPresidenteLabel = new javax.swing.JLabel();
        SecretarioLabel = new javax.swing.JLabel();
        EscrutinadoresLabel = new javax.swing.JLabel();
        ElComboBox = new javax.swing.JComboBox();
        FrComboBox = new javax.swing.JComboBox();
        NomePTextField = new javax.swing.JTextField();
        BIPTextField = new javax.swing.JTextField();
        BIVPTextField = new javax.swing.JTextField();
        NomeVPTextField = new javax.swing.JTextField();
        BISecTextField = new javax.swing.JTextField();
        NomeSecTextField = new javax.swing.JTextField();
        BIEscTextField = new javax.swing.JTextField();
        NomeEscTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollBar1 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Confirmar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1020, 571));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoCNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CNE.png"))); // NOI18N
        jLayeredPane1.add(LogoCNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        GerirActoEleitoral.setBackground(new java.awt.Color(255, 255, 255));
        GerirActoEleitoral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistarVotos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RegistarVotos.setText("Registar Votos");
        GerirActoEleitoral.add(RegistarVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        DeclararVencedor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        DeclararVencedor.setText("Declarar Vencedor");
        GerirActoEleitoral.add(DeclararVencedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, -1));

        AtribuirMandatos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AtribuirMandatos.setText("Atribuir Mandatos");
        GerirActoEleitoral.add(AtribuirMandatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 190, -1));

        GerarEstatísticas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        GerarEstatísticas.setText("Gerar Estatísticas");
        GerirActoEleitoral.add(GerarEstatísticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 190, -1));

        Back1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Back1.setText("Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        GerirActoEleitoral.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        GerarEstatísticasPanel.setBackground(new java.awt.Color(255, 255, 255));
        GerarEstatísticasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Confirmar3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Confirmar3.setText("Confirmar");

        Eleicao2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Eleicao2.setText("Eleição :");

        Lista2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Lista2.setText("Lista :");

        EleicaoComboBox2.setEditable(true);
        EleicaoComboBox2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        EleicaoComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ListaComboBox1.setEditable(true);
        ListaComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ListaComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ImagemListaLabel2.setText("jLabel4");

        CirculoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CirculoLabel.setText("Circulo :");

        CirculoComboBox.setEditable(true);
        CirculoComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CirculoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PercentagemTextField2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        PercentagemTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PercentagemTextField2.setText("%");
        PercentagemTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentagemTextField2ActionPerformed(evt);
            }
        });

        Percentagem1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Percentagem1.setText("Percentagem :");

        CandidatosLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CandidatosLabel1.setText("Candidatos :");

        CandidatosComboBox1.setEditable(true);
        CandidatosComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CandidatosComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CandidatosComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatosComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GerarEstatísticasPanelLayout = new javax.swing.GroupLayout(GerarEstatísticasPanel);
        GerarEstatísticasPanel.setLayout(GerarEstatísticasPanelLayout);
        GerarEstatísticasPanelLayout.setHorizontalGroup(
            GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerarEstatísticasPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerarEstatísticasPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Confirmar3)
                        .addGap(37, 37, 37))
                    .addGroup(GerarEstatísticasPanelLayout.createSequentialGroup()
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eleicao2)
                            .addComponent(Lista2)
                            .addComponent(CirculoLabel)
                            .addComponent(Percentagem1)
                            .addComponent(CandidatosLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EleicaoComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListaComboBox1, 0, 167, Short.MAX_VALUE)
                            .addComponent(CirculoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PercentagemTextField2)
                            .addComponent(CandidatosComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(ImagemListaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        GerarEstatísticasPanelLayout.setVerticalGroup(
            GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerarEstatísticasPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GerarEstatísticasPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImagemListaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(Confirmar3)
                        .addGap(40, 40, 40))
                    .addGroup(GerarEstatísticasPanelLayout.createSequentialGroup()
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eleicao2)
                            .addComponent(EleicaoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lista2)
                            .addComponent(ListaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CandidatosComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CandidatosLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CirculoLabel)
                            .addComponent(CirculoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(GerarEstatísticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Percentagem1)
                            .addComponent(PercentagemTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        GerirActoEleitoral.add(GerarEstatísticasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        RegistarVotosPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistarVotosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LocalizacaoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LocalizacaoLabel.setText("Localização :");

        VRLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        VRLabel.setText("Votos registados :");

        VVLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        VVLabel.setText("Votos validos :");

        LocalizacaoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        VRTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        VVTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        Confirmar2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Confirmar2.setText("Confirmar");

        SButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SButton.setText("...");

        javax.swing.GroupLayout RegistarVotosPanelLayout = new javax.swing.GroupLayout(RegistarVotosPanel);
        RegistarVotosPanel.setLayout(RegistarVotosPanelLayout);
        RegistarVotosPanelLayout.setHorizontalGroup(
            RegistarVotosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistarVotosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar2)
                .addGap(30, 30, 30))
            .addGroup(RegistarVotosPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(RegistarVotosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistarVotosPanelLayout.createSequentialGroup()
                        .addComponent(LocalizacaoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LocalizacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SButton)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(RegistarVotosPanelLayout.createSequentialGroup()
                        .addComponent(VRLabel)
                        .addGap(18, 18, 18)
                        .addComponent(VRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VVLabel)
                        .addGap(18, 18, 18)
                        .addComponent(VVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        RegistarVotosPanelLayout.setVerticalGroup(
            RegistarVotosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistarVotosPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(RegistarVotosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalizacaoLabel)
                    .addComponent(LocalizacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(RegistarVotosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VRLabel)
                    .addComponent(VVLabel)
                    .addComponent(VRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(Confirmar2)
                .addGap(33, 33, 33))
        );

        GerirActoEleitoral.add(RegistarVotosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        DeclararVencedorPanel.setBackground(new java.awt.Color(255, 255, 255));
        DeclararVencedorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Confirmar1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Confirmar1.setText("Confirmar");

        ImagemListaLabel1.setText("jLabel4");

        Lista1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Lista1.setText("Partidos :");

        PartidosComboBox1.setEditable(true);
        PartidosComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        PartidosComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PartidosComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidosComboBox1ActionPerformed(evt);
            }
        });

        Eleicao1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Eleicao1.setText("Eleição :");

        Percentagem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Percentagem.setText("Percentagem :");

        PercentagemTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        PercentagemTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PercentagemTextField1.setText("%");
        PercentagemTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentagemTextField1ActionPerformed(evt);
            }
        });

        EleicaoComboBox1.setEditable(true);
        EleicaoComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        EleicaoComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CandidatosLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CandidatosLabel.setText("Candidatos :");

        CandidatosComboBox.setEditable(true);
        CandidatosComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CandidatosComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CandidatosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeclararVencedorPanelLayout = new javax.swing.GroupLayout(DeclararVencedorPanel);
        DeclararVencedorPanel.setLayout(DeclararVencedorPanelLayout);
        DeclararVencedorPanelLayout.setHorizontalGroup(
            DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeclararVencedorPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eleicao1)
                    .addComponent(Lista1)
                    .addComponent(Percentagem)
                    .addComponent(CandidatosLabel))
                .addGap(88, 88, 88)
                .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CandidatosComboBox, 0, 167, Short.MAX_VALUE)
                    .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EleicaoComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PartidosComboBox1, 0, 167, Short.MAX_VALUE)
                        .addComponent(PercentagemTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(ImagemListaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeclararVencedorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar1)
                .addGap(24, 24, 24))
        );
        DeclararVencedorPanelLayout.setVerticalGroup(
            DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeclararVencedorPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeclararVencedorPanelLayout.createSequentialGroup()
                        .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eleicao1)
                            .addComponent(EleicaoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lista1)
                            .addComponent(PartidosComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CandidatosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CandidatosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DeclararVencedorPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImagemListaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(DeclararVencedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Percentagem)
                    .addComponent(PercentagemTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Confirmar1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        GerirActoEleitoral.add(DeclararVencedorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        AtribuirMandatosPanel.setBackground(new java.awt.Color(255, 255, 255));
        AtribuirMandatosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Eleicao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Eleicao.setText("Eleição :");

        Lista.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Lista.setText("Lista :");

        Deputados.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Deputados.setText("Deputados :");

        EleicaoComboBox.setEditable(true);
        EleicaoComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        EleicaoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ListaComboBox.setEditable(true);
        ListaComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ListaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DeputadosTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        DeputadosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeputadosTextFieldActionPerformed(evt);
            }
        });

        ImagemListaLabel.setText("jLabel4");

        Confirmar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Confirmar.setText("Confirmar");

        javax.swing.GroupLayout AtribuirMandatosPanelLayout = new javax.swing.GroupLayout(AtribuirMandatosPanel);
        AtribuirMandatosPanel.setLayout(AtribuirMandatosPanelLayout);
        AtribuirMandatosPanelLayout.setHorizontalGroup(
            AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtribuirMandatosPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eleicao)
                    .addComponent(Lista)
                    .addComponent(Deputados))
                .addGap(88, 88, 88)
                .addGroup(AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EleicaoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListaComboBox, 0, 167, Short.MAX_VALUE)
                    .addComponent(DeputadosTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(ImagemListaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtribuirMandatosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar)
                .addGap(24, 24, 24))
        );
        AtribuirMandatosPanelLayout.setVerticalGroup(
            AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtribuirMandatosPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtribuirMandatosPanelLayout.createSequentialGroup()
                        .addGroup(AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eleicao)
                            .addComponent(EleicaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lista)
                            .addComponent(ListaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AtribuirMandatosPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImagemListaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(AtribuirMandatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deputados)
                    .addComponent(DeputadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Confirmar)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        GerirActoEleitoral.add(AtribuirMandatosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        jLayeredPane1.add(GerirActoEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        ConfigurarActoEleitoral.setBackground(new java.awt.Color(255, 255, 255));
        ConfigurarActoEleitoral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistarEleição.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RegistarEleição.setText("Registar Eleição");
        RegistarEleição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarEleiçãoActionPerformed(evt);
            }
        });
        ConfigurarActoEleitoral.add(RegistarEleição, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        AdicionarListas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AdicionarListas.setText("Adicionar Listas");
        ConfigurarActoEleitoral.add(AdicionarListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, -1));

        AdicionarCandidatos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AdicionarCandidatos.setText("Adicionar Candidatos");
        ConfigurarActoEleitoral.add(AdicionarCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 190, -1));

        AdicionarVotantes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AdicionarVotantes.setText("Adicionar Votantes");
        ConfigurarActoEleitoral.add(AdicionarVotantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 190, -1));

        GerirAssembleias.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        GerirAssembleias.setText("Gerir Assembleias");
        ConfigurarActoEleitoral.add(GerirAssembleias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 190, -1));

        Back.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        ConfigurarActoEleitoral.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        AdicionarCandidatosPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdicionarCandidatosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Confirmar7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Confirmar7.setText("Confirmar");

        EleiçãoLabel1.setText("Eleição :");

        BILabel.setText("BI :");

        NomeLabel.setText("Nome :");

        DataLabel.setText("Data :");

        ArquivoLabel.setText("Arquivo :");

        DatadeNascimentoLabel.setText("Data de Nascimento :");

        NaturalidadeLabel.setText("Naturalidade :");

        Filiação.setText("Filição :");

        Morada.setText("Morada :");

        EleiçãoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eleições", " " }));

        RuaTextField3.setText("Rua");

        LocalidadeTextField4.setText("Localidade");

        CodigoPostalTextField.setText("Codigo Postal");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia" }));

        javax.swing.GroupLayout AdicionarCandidatosPanelLayout = new javax.swing.GroupLayout(AdicionarCandidatosPanel);
        AdicionarCandidatosPanel.setLayout(AdicionarCandidatosPanelLayout);
        AdicionarCandidatosPanelLayout.setHorizontalGroup(
            AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarCandidatosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar7)
                .addGap(54, 54, 54))
            .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EleiçãoLabel1)
                            .addComponent(Filiação))
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EleiçãoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(FiliaçãoTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addComponent(Morada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RuaTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(LocalidadeTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLabel)
                            .addComponent(BILabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                                .addComponent(BITextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(DataLabel))
                            .addComponent(NomeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarCandidatosPanelLayout.createSequentialGroup()
                                .addComponent(DatadeNascimentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addComponent(NaturalidadeLabel)
                        .addGap(3, 3, 3)
                        .addComponent(NaturalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(ArquivoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArquivoTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CodigoPostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        AdicionarCandidatosPanelLayout.setVerticalGroup(
            AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarCandidatosPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EleiçãoLabel1)
                    .addComponent(EleiçãoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BILabel)
                    .addComponent(DataLabel)
                    .addComponent(ArquivoLabel)
                    .addComponent(BITextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArquivoTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeLabel)
                            .addComponent(NomeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdicionarCandidatosPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatadeNascimentoLabel)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Morada)
                    .addComponent(RuaTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocalidadeTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoPostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NaturalidadeLabel)
                    .addComponent(NaturalidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(AdicionarCandidatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Filiação)
                    .addComponent(FiliaçãoTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(Confirmar7)
                .addGap(34, 34, 34))
        );

        ConfigurarActoEleitoral.add(AdicionarCandidatosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        RegistarEleiçãoPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistarEleiçãoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Confirmar5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Confirmar5.setText("Confirmar");

        EleiçãoComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eleições", " " }));

        EleiçãoLabel2.setText("Eleição :");

        DataLabel1.setText("Data :");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano" }));

        EleiçãoLabel3.setText("Eleição :");

        EleiçãoComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eleições", " " }));

        javax.swing.GroupLayout RegistarEleiçãoPanelLayout = new javax.swing.GroupLayout(RegistarEleiçãoPanel);
        RegistarEleiçãoPanel.setLayout(RegistarEleiçãoPanelLayout);
        RegistarEleiçãoPanelLayout.setHorizontalGroup(
            RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistarEleiçãoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistarEleiçãoPanelLayout.createSequentialGroup()
                        .addComponent(DataLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistarEleiçãoPanelLayout.createSequentialGroup()
                        .addComponent(EleiçãoLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleiçãoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistarEleiçãoPanelLayout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addGroup(RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistarEleiçãoPanelLayout.createSequentialGroup()
                        .addComponent(Confirmar5)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistarEleiçãoPanelLayout.createSequentialGroup()
                        .addComponent(EleiçãoLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleiçãoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        RegistarEleiçãoPanelLayout.setVerticalGroup(
            RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistarEleiçãoPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EleiçãoLabel2)
                    .addComponent(EleiçãoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EleiçãoLabel3)
                    .addComponent(EleiçãoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(RegistarEleiçãoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataLabel1)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addComponent(Confirmar5)
                .addContainerGap())
        );

        ConfigurarActoEleitoral.add(RegistarEleiçãoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        AdicionarListasPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdicionarListasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Confirmar6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Confirmar6.setText("Confirmar");

        jLabel1.setText("Eleição :");

        jLabel2.setText("Nome : ");

        jLabel3.setText("Círculo :");

        jLabel4.setText("Deputados");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Deputado 1", "Deputado 2", "Deputado 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel5.setText("Delegados");

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Delegado 1", "Delegado 2", "Delegado 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome :");

        jLabel7.setText("BI");

        javax.swing.GroupLayout AdicionarListasPanelLayout = new javax.swing.GroupLayout(AdicionarListasPanel);
        AdicionarListasPanel.setLayout(AdicionarListasPanelLayout);
        AdicionarListasPanelLayout.setHorizontalGroup(
            AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarListasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarListasPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar6)
                .addGap(88, 88, 88))
            .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3))))
                    .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarListasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)))
                .addGap(192, 192, 192))
        );
        AdicionarListasPanelLayout.setVerticalGroup(
            AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 72, Short.MAX_VALUE))
                            .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(AdicionarListasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Confirmar6))))
                    .addGroup(AdicionarListasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addContainerGap())
        );

        ConfigurarActoEleitoral.add(AdicionarListasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        AdicionarVotantesPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdicionarVotantesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Confirmar8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Confirmar8.setText("Confirmar");

        javax.swing.GroupLayout AdicionarVotantesPanelLayout = new javax.swing.GroupLayout(AdicionarVotantesPanel);
        AdicionarVotantesPanel.setLayout(AdicionarVotantesPanelLayout);
        AdicionarVotantesPanelLayout.setHorizontalGroup(
            AdicionarVotantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarVotantesPanelLayout.createSequentialGroup()
                .addContainerGap(595, Short.MAX_VALUE)
                .addComponent(Confirmar8)
                .addGap(32, 32, 32))
        );
        AdicionarVotantesPanelLayout.setVerticalGroup(
            AdicionarVotantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdicionarVotantesPanelLayout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(Confirmar8)
                .addContainerGap())
        );

        ConfigurarActoEleitoral.add(AdicionarVotantesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        GerirAssembleiasPanel.setBackground(new java.awt.Color(255, 255, 255));
        GerirAssembleiasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EleicaoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        EleicaoLabel.setText("Eleição :");

        FreguesiaLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FreguesiaLabel.setText("Freguesia :");

        PresidenteLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PresidenteLabel.setText("Presidente :");

        VPresidenteLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        VPresidenteLabel.setText("V.Presidente :");

        SecretarioLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SecretarioLabel.setText("Secretário :");

        EscrutinadoresLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        EscrutinadoresLabel.setText("Escrutinadores :");

        ElComboBox.setEditable(true);
        ElComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ElComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FrComboBox.setEditable(true);
        FrComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        FrComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        NomePTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        NomePTextField.setText("Nome");

        BIPTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BIPTextField.setText("BI");

        BIVPTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BIVPTextField.setText("BI");

        NomeVPTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        NomeVPTextField.setText("Nome");

        BISecTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BISecTextField.setText("BI");

        NomeSecTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        NomeSecTextField.setText("Nome");

        BIEscTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BIEscTextField.setText("BI");

        NomeEscTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        NomeEscTextField.setText("Nome");

        jList1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1.setText("«");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton3.setText("»");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Confirmar4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Confirmar4.setText("Confirmar");

        javax.swing.GroupLayout GerirAssembleiasPanelLayout = new javax.swing.GroupLayout(GerirAssembleiasPanel);
        GerirAssembleiasPanel.setLayout(GerirAssembleiasPanelLayout);
        GerirAssembleiasPanelLayout.setHorizontalGroup(
            GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VPresidenteLabel)
                    .addComponent(SecretarioLabel)
                    .addComponent(EscrutinadoresLabel)
                    .addComponent(EleicaoLabel)
                    .addComponent(PresidenteLabel)
                    .addComponent(FreguesiaLabel))
                .addGap(30, 30, 30)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ElComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FrComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                        .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NomeVPTextField)
                                .addComponent(NomeSecTextField)
                                .addComponent(NomePTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jButton1))
                            .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(49, 49, 49)
                        .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BISecTextField)
                                .addComponent(BIVPTextField)
                                .addComponent(BIPTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addComponent(BIEscTextField))
                            .addComponent(NomeEscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerirAssembleiasPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmar4)
                .addGap(45, 45, 45))
        );
        GerirAssembleiasPanelLayout.setVerticalGroup(
            GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EleicaoLabel)
                    .addComponent(ElComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FreguesiaLabel)
                    .addComponent(FrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PresidenteLabel)
                    .addComponent(NomePTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VPresidenteLabel)
                    .addComponent(NomeVPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIVPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecretarioLabel)
                    .addComponent(NomeSecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BISecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(EscrutinadoresLabel)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(GerirAssembleiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                                .addComponent(NomeEscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BIEscTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GerirAssembleiasPanelLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(Confirmar4)
                .addGap(25, 25, 25))
        );

        ConfigurarActoEleitoral.add(GerirAssembleiasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 720, 570));

        jLayeredPane1.add(ConfigurarActoEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarEleiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarEleiçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistarEleiçãoActionPerformed

    private void DeputadosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeputadosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeputadosTextFieldActionPerformed

    private void PercentagemTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentagemTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PercentagemTextField1ActionPerformed

    private void PartidosComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidosComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidosComboBox1ActionPerformed

    private void CandidatosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidatosComboBoxActionPerformed

    private void PercentagemTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentagemTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PercentagemTextField2ActionPerformed

    private void CandidatosComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatosComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidatosComboBox1ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        mainFrame.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Back1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        mainFrame.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

     public void VisibleCAE(){
            GerirActoEleitoral.setVisible(false);
            AdicionarCandidatosPanel.setVisible(false);
            RegistarEleiçãoPanel.setVisible(false);
            AdicionarListasPanel.setVisible(false);
            AdicionarVotantesPanel.setVisible(false);
            GerirAssembleiasPanel.setVisible(false);
            GerarEstatísticasPanel.setVisible(false);
            RegistarVotosPanel.setVisible(false);
            DeclararVencedorPanel.setVisible(false);
            AtribuirMandatosPanel.setVisible(false);
            
     }
    
    public void VisibleGAE(){
            ConfigurarActoEleitoral.setVisible(false);
            GerarEstatísticasPanel.setVisible(false);
            RegistarVotosPanel.setVisible(false);
            DeclararVencedorPanel.setVisible(false);
            AtribuirMandatosPanel.setVisible(false);
            AdicionarCandidatosPanel.setVisible(false);
            RegistarEleiçãoPanel.setVisible(false);
            AdicionarListasPanel.setVisible(false);
            AdicionarVotantesPanel.setVisible(false);
            GerirAssembleiasPanel.setVisible(false);
    }/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarCandidatos;
    private javax.swing.JPanel AdicionarCandidatosPanel;
    private javax.swing.JButton AdicionarListas;
    private javax.swing.JPanel AdicionarListasPanel;
    private javax.swing.JButton AdicionarVotantes;
    private javax.swing.JPanel AdicionarVotantesPanel;
    private javax.swing.JLabel ArquivoLabel;
    private javax.swing.JTextField ArquivoTextField8;
    private javax.swing.JButton AtribuirMandatos;
    private javax.swing.JPanel AtribuirMandatosPanel;
    private javax.swing.JTextField BIEscTextField;
    private javax.swing.JLabel BILabel;
    private javax.swing.JTextField BIPTextField;
    private javax.swing.JTextField BISecTextField;
    private javax.swing.JTextField BITextField1;
    private javax.swing.JTextField BIVPTextField;
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JComboBox CandidatosComboBox;
    private javax.swing.JComboBox CandidatosComboBox1;
    private javax.swing.JLabel CandidatosLabel;
    private javax.swing.JLabel CandidatosLabel1;
    private javax.swing.JComboBox CirculoComboBox;
    private javax.swing.JLabel CirculoLabel;
    private javax.swing.JTextField CodigoPostalTextField;
    private javax.swing.JPanel ConfigurarActoEleitoral;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Confirmar1;
    private javax.swing.JButton Confirmar2;
    private javax.swing.JButton Confirmar3;
    private javax.swing.JButton Confirmar4;
    private javax.swing.JButton Confirmar5;
    private javax.swing.JButton Confirmar6;
    private javax.swing.JButton Confirmar7;
    private javax.swing.JButton Confirmar8;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JLabel DataLabel1;
    private javax.swing.JLabel DatadeNascimentoLabel;
    private javax.swing.JButton DeclararVencedor;
    private javax.swing.JPanel DeclararVencedorPanel;
    private javax.swing.JLabel Deputados;
    private javax.swing.JTextField DeputadosTextField;
    private javax.swing.JComboBox ElComboBox;
    private javax.swing.JLabel Eleicao;
    private javax.swing.JLabel Eleicao1;
    private javax.swing.JLabel Eleicao2;
    private javax.swing.JComboBox EleicaoComboBox;
    private javax.swing.JComboBox EleicaoComboBox1;
    private javax.swing.JComboBox EleicaoComboBox2;
    private javax.swing.JLabel EleicaoLabel;
    private javax.swing.JComboBox EleiçãoComboBox;
    private javax.swing.JComboBox EleiçãoComboBox1;
    private javax.swing.JComboBox EleiçãoComboBox2;
    private javax.swing.JLabel EleiçãoLabel1;
    private javax.swing.JLabel EleiçãoLabel2;
    private javax.swing.JLabel EleiçãoLabel3;
    private javax.swing.JLabel EscrutinadoresLabel;
    private javax.swing.JLabel Filiação;
    private javax.swing.JTextField FiliaçãoTextField7;
    private javax.swing.JComboBox FrComboBox;
    private javax.swing.JLabel FreguesiaLabel;
    private javax.swing.JButton GerarEstatísticas;
    private javax.swing.JPanel GerarEstatísticasPanel;
    private javax.swing.JPanel GerirActoEleitoral;
    private javax.swing.JButton GerirAssembleias;
    private javax.swing.JPanel GerirAssembleiasPanel;
    private javax.swing.JLabel ImagemListaLabel;
    private javax.swing.JLabel ImagemListaLabel1;
    private javax.swing.JLabel ImagemListaLabel2;
    private javax.swing.JLabel Lista;
    private javax.swing.JLabel Lista1;
    private javax.swing.JLabel Lista2;
    private javax.swing.JComboBox ListaComboBox;
    private javax.swing.JComboBox ListaComboBox1;
    private javax.swing.JTextField LocalidadeTextField4;
    private javax.swing.JLabel LocalizacaoLabel;
    private javax.swing.JTextField LocalizacaoTextField;
    private javax.swing.JLabel LogoCNE;
    private javax.swing.JLabel Morada;
    private javax.swing.JLabel NaturalidadeLabel;
    private javax.swing.JTextField NaturalidadeTextField;
    private javax.swing.JTextField NomeEscTextField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomePTextField;
    private javax.swing.JTextField NomeSecTextField;
    private javax.swing.JTextField NomeTextField2;
    private javax.swing.JTextField NomeVPTextField;
    private javax.swing.JComboBox PartidosComboBox1;
    private javax.swing.JLabel Percentagem;
    private javax.swing.JLabel Percentagem1;
    private javax.swing.JTextField PercentagemTextField1;
    private javax.swing.JTextField PercentagemTextField2;
    private javax.swing.JLabel PresidenteLabel;
    private javax.swing.JButton RegistarEleição;
    private javax.swing.JPanel RegistarEleiçãoPanel;
    private javax.swing.JButton RegistarVotos;
    private javax.swing.JPanel RegistarVotosPanel;
    private javax.swing.JTextField RuaTextField3;
    private javax.swing.JButton SButton;
    private javax.swing.JLabel SecretarioLabel;
    private javax.swing.JLabel VPresidenteLabel;
    private javax.swing.JLabel VRLabel;
    private javax.swing.JTextField VRTextField;
    private javax.swing.JLabel VVLabel;
    private javax.swing.JTextField VVTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
